import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {dayKey,validateRecord,latest,leaderboard} from '../google/domain.js';
import {environment} from './helpers/google-environment.mjs';
const image='data:image/jpeg;base64,'+Buffer.from([255,216,255,192,0,17,8,0,100,0,100,3,1,17,0,2,17,0,3,17,0,255,218,0,2,255,217]).toString('base64');
test('Google backend rejects missing, expired, wrong-audience and non-admin Google identities',()=>{
  const env=environment();
  for(const identity of [null,env.auth('invalid','line'),env.auth('expired','line'),env.auth('wrongaud','line'),env.auth('other','google')])assert.equal(env.call('bootstrap',{},identity).ok,false);
  assert.equal(env.call('bootstrap').data.role,'admin');
});
test('one-use invitation binds a LINE identity and cannot be stolen/reused',()=>{
  const e=environment(),p=e.patient('A');
  assert.equal(e.call('bind',{code:p.code,nickname:'其他帳號'},e.auth('B','line')).ok,false);
  assert.equal(e.call('bootstrap',{},p.identity).data.profile.id,p.id);
  assert.equal(e.call('admin.patients',{},p.identity).ok,false);
  assert.equal(e.call('save',{patientId:p.id},e.auth('unbound','line')).ok,false);
});
test('test patient completes three tasks; saves survive bootstrap; photos are owner/admin only',()=>{
  const e=environment(),p=e.patient('A'),other=e.patient('B'),date=dayKey();
  const examples=[{kind:'exercise',date,mode:'steps',value:1616,activity:'步行',recognized:1616},{kind:'meal',date,period:'午餐',groups:['主食','蔬菜'],eaten:'全部',drink:'無飲料',restrictedDiet:false},{kind:'medicine',date,status:'未服用'}];
  for(const record of examples){const result=e.call('save',{record,requestId:randomUUID(),image:record.kind==='medicine'?null:image},p.identity);assert.equal(result.ok,true,result.error);}
  const records=e.call('bootstrap',{},p.identity).data.records;assert.equal(records.length,3);
  assert.equal(e.call('bootstrap',{},other.identity).data.records.length,0);
  assert.equal(e.call('image',{id:records[0].id},p.identity).ok,true);
  assert.equal(e.call('image',{id:records[0].id},other.identity).ok,false);
  assert.equal(e.call('image',{id:records[0].id}).ok,true);
  assert.equal(e.call('admin.records',{patientId:p.id}).data.records.length,3);
  assert.equal('imageFileId' in records[0],false);
});
test('idempotent retry makes one record; corrections preserve history and replace daily total',()=>{
  const e=environment(),p=e.patient('A',false),date=dayKey(),requestId=randomUUID();
  const record={kind:'exercise',date,mode:'steps',value:1616,activity:'步行',recognized:1616};
  const body={record,requestId,image};const saved=e.call('save',body,p.identity).data.record;
  assert.equal(e.call('save',body,p.identity).data.record.id,saved.id);
  assert.equal(e.call('save',{...body,record:{...record,value:1700}},p.identity).ok,false);
  const revised=e.call('save',{record:{...record,value:2000},previousId:saved.id,requestId:randomUUID()},p.identity);assert.equal(revised.ok,true,revised.error);
  assert.equal(revised.data.record.manuallyCorrected,true);
  assert.equal(e.call('bootstrap',{},p.identity).data.records.length,1);
  assert.equal(e.call('admin.records',{patientId:p.id}).data.records.length,2);
  assert.equal(e.call('save',{record,previousId:saved.id,requestId:randomUUID()},p.identity).ok,false);
  e.call('profile',{nickname:'參賽者'},p.identity);
  assert.equal(e.call('leaderboard',{},p.identity).data.rows[0].steps,2000);
});
test('all real patients enter the nickname leaderboard; test patients never enter',()=>{
  const e=environment(),p=e.patient('A');e.call('profile',{nickname:'測試暱稱'},p.identity);
  e.call('save',{record:{kind:'exercise',date:dayKey(),mode:'steps',value:1000,activity:'步行'},requestId:randomUUID(),image},p.identity);
  assert.deepEqual(e.call('leaderboard',{},p.identity).data.rows,[]);
  const real=e.patient('REAL',false);e.call('profile',{nickname:'正式暱稱'},real.identity);
  e.call('save',{record:{kind:'exercise',date:dayKey(),mode:'steps',value:1234,activity:'步行'},requestId:randomUUID(),image},real.identity);
  const current=e.books.get(e.properties.get('PATIENT_SHEET_ID')).getSheetByName('Patients').rows;
  const stored=JSON.parse(current[2][5]);stored.participating=false;current[2][5]=JSON.stringify(stored);
  assert.deepEqual(e.call('leaderboard',{},real.identity).data.rows,[{nickname:'正式暱稱',steps:1234}]);
});
test('ordinary JPEG metadata is accepted after private upload checks',()=>{
  const e=environment();
  const bytes=Buffer.from(image.split(',')[1],'base64');
  const withMetadata=Buffer.concat([bytes.subarray(0,2),Buffer.from([255,225,0,4,0,0]),bytes.subarray(2)]);
  const value='data:image/jpeg;base64,'+withMetadata.toString('base64');
  assert.equal(e.context.HealthVoyage.validateImage(value).width,100);
});
test('closed enrollment permits only scoped test patients, invalid images fail closed',()=>{
  const e=environment(),p=e.patient('A'),real=e.patient('REAL',false);e.properties.set('ACCEPT_PATIENTS','false');e.properties.set('ACCEPT_TEST_PATIENTS','false');assert.equal(e.call('bootstrap',{},p.identity).ok,false);
  assert.equal(e.call('bootstrap').ok,true);
  e.properties.set('ACCEPT_TEST_PATIENTS','true');
  assert.equal(e.call('bootstrap',{},p.identity).ok,true);
  assert.equal(e.call('bootstrap',{},real.identity).ok,false);
  const unbound=e.auth('new-test','line');assert.equal(e.call('bootstrap',{},unbound).data.bound,false);
  assert.equal(e.call('bind',{code:'0000000000000000',nickname:'測試新手'},unbound).ok,false);
  const record={kind:'exercise',date:dayKey(),mode:'steps',value:0,activity:'休息'};
  assert.equal(e.call('save',{record,requestId:randomUUID(),image:'data:image/jpeg;base64,AAAA'},p.identity).ok,false);
  assert.equal(e.call('save',{record,requestId:randomUUID()},p.identity).ok,false);
});
test('real Taiwan day, future dates, integer ranges and single metric validated',()=>{
  assert.equal(dayKey(new Date('2026-09-03T16:01:00Z')),'2026-09-04');
  for(const date of ['2026-09-04','2026-02-31','wrong'])assert.throws(()=>validateRecord({kind:'medicine',date,status:'已服用'},'2026-09-03'));
  assert.throws(()=>validateRecord({kind:'exercise',date:'2026-09-03',mode:'minutes',value:1.5,activity:'步行'},'2026-09-03'));
  const value=validateRecord({kind:'exercise',date:'2026-09-03',mode:'minutes',value:30,activity:'步行',steps:999999},'2026-09-03');assert.equal('steps' in value,false);
});

test('activity goals are admin-only, private to each patient and preserved across profile edits',()=>{
  const e=environment(),p=e.patient('A'),other=e.patient('B');
  const body={patientId:p.id,steps:3000,previousId:null,requestId:randomUUID()};
  assert.equal(e.call('admin.activityGoal',body,p.identity).ok,false);
  const saved=e.call('admin.activityGoal',body);assert.equal(saved.ok,true,saved.error);
  const goals=saved.data.profile.activityGoals;
  assert.equal(goals[0].effectiveFrom,dayKey());assert.equal(goals[0].steps,3000);
  assert.deepEqual(Object.keys(goals[0]).sort(),['effectiveFrom','id','steps']);
  assert.deepEqual(e.call('bootstrap',{},p.identity).data.profile.activityGoals,goals);
  assert.deepEqual(e.call('bootstrap',{patientId:p.id},other.identity).data.profile.activityGoals,[]);
  const forged=e.call('profile',{nickname:'新暱稱',activityGoals:[{steps:1}]},p.identity);
  assert.deepEqual(forged.data.profile.activityGoals,goals);
  const auditRows=e.books.get(e.properties.get('RECORD_SHEET_ID')).getSheetByName('Audit').rows.slice(1).map(r=>JSON.parse(r[4]));
  const audit=auditRows.find(r=>r.action==='activityGoal.update');
  assert.equal(audit.target,p.id);assert.equal(audit.details.steps,3000);assert.equal(audit.details.goalId,goals[0].id);
});
test('goal retry is idempotent, stale writes conflict, history retained and changes start tomorrow',()=>{
  const e=environment(),p=e.patient('A'),body={patientId:p.id,steps:3000,previousId:null,requestId:randomUUID()};
  const first=e.call('admin.activityGoal',body).data.profile.activityGoals[0];
  assert.equal(e.call('admin.activityGoal',body).data.profile.activityGoals.length,1);
  assert.equal(e.call('admin.activityGoal',{...body,steps:4000}).ok,false);
  assert.equal(e.call('admin.activityGoal',{...body,steps:4000,requestId:randomUUID()}).ok,false);
  const second=e.call('admin.activityGoal',{...body,steps:4000,previousId:first.id,requestId:randomUUID(),effectiveFrom:'2000-01-01'}).data.profile.activityGoals;
  assert.equal(second.length,2);assert.deepEqual(second[0],first);
  const tomorrow=new Date(Date.parse(dayKey()+'T00:00:00Z')+86400000).toISOString().slice(0,10);
  assert.equal(second[1].effectiveFrom,tomorrow);
  const paused=e.call('admin.activityGoal',{...body,steps:null,previousId:second[1].id,requestId:randomUUID()}).data.profile.activityGoals;
  assert.equal(paused.length,3);assert.equal(paused[2].steps,null);assert.equal(paused[2].effectiveFrom,tomorrow);
  assert.equal(e.call('admin.activityGoal',body).data.profile.activityGoals.length,3);
});
test('invalid and inactive patient goals fail without writes; service advertises goal capability',()=>{
  const e=environment(),p=e.patient('A');
  for(const steps of [null,0,-1,1.2,100001,'3000',undefined])assert.equal(e.call('admin.activityGoal',{patientId:p.id,steps,requestId:randomUUID()}).ok,false);
  assert.equal(e.call('admin.activityGoal',{patientId:'missing',steps:3000,requestId:randomUUID()}).ok,false);
  const row=e.books.get(e.properties.get('PATIENT_SHEET_ID')).getSheetByName('Patients').rows[1];
  const stored=JSON.parse(row[5]);stored.active=false;row[5]=JSON.stringify(stored);
  assert.equal(e.call('admin.activityGoal',{patientId:p.id,steps:3000,requestId:randomUUID()}).ok,false);
  assert.equal(JSON.parse(row[5]).activityGoals,undefined);
  assert.deepEqual(JSON.parse(e.context.HealthVoyage.get().text).capabilities,['activityGoals','adminTrash','medicationPlans']);
});

test('admin deletes the daily record without revealing older revisions; photos and audit survive',()=>{
  const e=environment(),p=e.patient('A',false),other=e.patient('B'),date=dayKey();
  const body={record:{kind:'exercise',date,mode:'steps',value:1200,activity:'步行'},requestId:randomUUID(),image};
  const first=e.call('save',body,p.identity).data.record;
  const second=e.call('save',{record:{...body.record,value:1600},previousId:first.id,requestId:randomUUID()},p.identity).data.record;
  const change={id:second.id,deleted:true,requestId:randomUUID()};
  assert.equal(e.call('admin.recordStatus',change,p.identity).ok,false);
  assert.equal(e.call('admin.recordStatus',change,other.identity).ok,false);
  const removed=e.call('admin.recordStatus',change);assert.equal(removed.ok,true,removed.error);
  const tombstone=removed.data.records.at(-1);assert.ok(tombstone.deletedAt);
  assert.equal(e.call('bootstrap',{},p.identity).data.records.length,0);
  assert.equal(e.call('leaderboard',{},p.identity).data.rows[0].steps,0);
  assert.equal(e.call('image',{id:first.id},p.identity).ok,false);
  assert.equal(e.call('image',{id:second.id},p.identity).ok,false);
  assert.equal(e.call('image',{id:first.id}).ok,true);assert.equal(e.files.size,1);
  assert.equal(e.call('admin.recordStatus',change).data.records.length,3);
  assert.equal(e.call('save',body,p.identity).ok,false);
  assert.equal(e.call('save',{record:body.record,previousId:second.id,requestId:randomUUID()},p.identity).ok,false);
  const restored=e.call('admin.recordStatus',{id:tombstone.id,deleted:false,requestId:randomUUID()});assert.equal(restored.ok,true,restored.error);
  const live=e.call('bootstrap',{},p.identity).data.records;
  assert.equal(live.length,1);assert.equal(live[0].value,1600);assert.equal(live[0].deletedAt,null);assert.equal('adminMutation' in live[0],false);
  assert.equal(e.call('image',{id:first.id},p.identity).ok,true);
  assert.equal(e.call('leaderboard',{},p.identity).data.rows[0].steps,1600);
  const audit=e.books.get(e.properties.get('RECORD_SHEET_ID')).getSheetByName('Audit').rows.slice(1).map(r=>JSON.parse(r[4]));
  assert.equal(audit.filter(r=>r.action==='record.delete').length,1);assert.equal(audit.filter(r=>r.action==='record.restore').length,1);
});
test('deleted records may be replaced with fresh evidence; stale restore cannot overwrite the replacement',()=>{
  const e=environment(),p=e.patient('A'),record={kind:'exercise',date:dayKey(),mode:'steps',value:1200,activity:'步行'};
  const first=e.call('save',{record,image,requestId:randomUUID()},p.identity).data.record;
  const body={id:first.id,deleted:true,requestId:randomUUID()};
  const deleted=e.call('admin.recordStatus',body).data.records.at(-1);
  const fresh=e.call('save',{record:{...record,value:500},image,requestId:randomUUID()},p.identity);assert.equal(fresh.ok,true,fresh.error);
  assert.equal(e.call('admin.recordStatus',{id:deleted.id,deleted:false,requestId:randomUUID()}).ok,false);
  assert.equal(e.call('admin.recordStatus',{...body,deleted:false}).ok,false);
  assert.equal(e.call('admin.recordStatus',body).data.records.length,3);
  assert.equal(e.call('bootstrap',{},p.identity).data.records[0].value,500);
  assert.equal(e.call('image',{id:first.id},p.identity).ok,false);
  assert.equal(e.call('image',{id:fresh.data.record.id},p.identity).ok,true);
});
test('deleted patients lose all patient access, stay bound and restore their prior records',()=>{
  const e=environment(),p=e.patient('A',false),other=e.patient('B');
  const record={kind:'exercise',date:dayKey(),mode:'steps',value:1500,activity:'步行'};
  const first=e.call('save',{record,image,requestId:randomUUID()},p.identity).data.record;
  const body={patientId:p.id,deleted:true,previousVersion:null,requestId:randomUUID()};
  assert.equal(e.call('admin.patientStatus',body,p.identity).ok,false);
  const deleted=e.call('admin.patientStatus',body);assert.equal(deleted.ok,true,deleted.error);assert.equal(deleted.data.patient.active,false);
  for(const [action,payload] of [['bootstrap',{}],['profile',{nickname:'改暱稱'}],['image',{id:first.id}],['leaderboard',{}],['save',{record,image,requestId:randomUUID()}],['bind',{code:p.code,nickname:'重新綁定'}]])assert.equal(e.call(action,payload,p.identity).ok,false,action);
  assert.equal(e.call('leaderboard',{},other.identity).data.rows.length,0);
  assert.equal(e.call('admin.records',{patientId:p.id}).data.records.length,1);
  assert.equal(e.call('image',{id:first.id}).ok,true);
  assert.equal(e.call('admin.recordStatus',{id:first.id,deleted:true,requestId:randomUUID()}).ok,false);
  assert.equal(e.call('admin.activityGoal',{patientId:p.id,steps:3000,requestId:randomUUID()}).ok,false);
  assert.equal(e.call('admin.patientStatus',body).data.patient.stateVersion,deleted.data.patient.stateVersion);
  assert.equal(e.call('admin.patientStatus',{...body,deleted:false,requestId:randomUUID()}).ok,false);
  const restored=e.call('admin.patientStatus',{patientId:p.id,deleted:false,previousVersion:deleted.data.patient.stateVersion,requestId:randomUUID()});assert.equal(restored.ok,true,restored.error);
  assert.equal(restored.data.patient.bound,true);assert.equal(restored.data.patient.active,true);
  assert.equal(e.call('bootstrap',{},p.identity).data.records[0].id,first.id);
  assert.equal(e.call('admin.patientStatus',body).data.patient.deletedAt,null);
});
test('patient restore never reactivates a separately disabled account or restores individually deleted records',()=>{
  const e=environment(),p=e.patient('A'),date=dayKey();
  const r=e.call('save',{record:{kind:'medicine',date,status:'未服用'},requestId:randomUUID()},p.identity).data.record;
  e.call('admin.recordStatus',{id:r.id,deleted:true,requestId:randomUUID()});
  const deleted=e.call('admin.patientStatus',{patientId:p.id,deleted:true,requestId:randomUUID()}).data.patient;
  const restored=e.call('admin.patientStatus',{patientId:p.id,deleted:false,previousVersion:deleted.stateVersion,requestId:randomUUID()});assert.equal(restored.ok,true);
  assert.equal(e.call('bootstrap',{},p.identity).data.records.length,0);
  const rows=e.books.get(e.properties.get('PATIENT_SHEET_ID')).getSheetByName('Patients').rows;
  const saved=JSON.parse(rows[1][5]);saved.active=false;rows[1][5]=JSON.stringify(saved);
  const again=e.call('admin.patientStatus',{patientId:p.id,deleted:true,previousVersion:restored.data.patient.stateVersion,requestId:randomUUID()}).data.patient;
  assert.equal(e.call('admin.patientStatus',{patientId:p.id,deleted:false,previousVersion:again.stateVersion,requestId:randomUUID()}).data.patient.active,false);
});
test('deleted unbound invitation is unavailable and malformed mutations fail closed',()=>{
  const e=environment(),created=e.call('admin.createPatient',{name:'未綁定測試',isTest:true,requestId:randomUUID()}).data;
  assert.equal(e.call('admin.patientStatus',{patientId:created.patient.id,deleted:'true',requestId:randomUUID()}).ok,false);
  assert.equal(e.call('admin.recordStatus',{id:'missing',deleted:true,requestId:randomUUID()}).ok,false);
  const deleted=e.call('admin.patientStatus',{patientId:created.patient.id,deleted:true,requestId:randomUUID()});assert.equal(deleted.ok,true);
  assert.equal(e.call('bind',{code:created.code,nickname:'測試新人'},e.auth('new','line')).ok,false);
  e.properties.set('ACCEPT_PATIENTS','false');e.properties.set('ACCEPT_TEST_PATIENTS','true');
  assert.equal(e.call('bind',{code:created.code,nickname:'測試新人'},e.auth('new','line')).ok,false);
});
